# Validation des données

## Étude des contenus d’entrée

In [1]:
from lxml import objectify
import pandas as pd

xml = objectify.parse(open('XMLData2.xml'))
root = xml.getroot()
df = pd.DataFrame(columns=('Number', 'String', 'Boolean'))

for i in range(0,4):
    obj = root.getchildren()[i].getchildren()
    row = dict(zip(['Number', 'String', 'Boolean'],
                   [obj[0].text, obj[1].text,
                    obj[2].text]))
    row_s = pd.Series(row)
    row_s.name = i
    df = df.append(row_s)

search = pd.DataFrame.duplicated(df)
print(df)
print()
print(search[search == True])

  Number   String Boolean
0      1    Primo    True
1      2  Secundo   False
2      3   Tercio    True
3      3   Tercio    True

3    True
dtype: bool


## Suppression d’un doublon

In [2]:
from lxml import objectify
import pandas as pd

xml = objectify.parse(open('XMLData2.xml'))
root = xml.getroot()
df = pd.DataFrame(columns=('Number', 'String', 'Boolean'))
for i in range(0,4):
    obj = root.getchildren()[i].getchildren()
    row = dict(zip(['Number', 'String', 'Boolean'],
                   [obj[0].text, obj[1].text,
                    obj[2].text]))
    row_s = pd.Series(row)
    row_s.name = i
    df = df.append(row_s)

print(df.drop_duplicates())

  Number   String Boolean
0      1    Primo    True
1      2  Secundo   False
2      3   Tercio    True


## Création d’une data map et d’un plan de données

In [3]:
import pandas as pd
pd.set_option('display.width', 55)

df = pd.DataFrame({'A': [0,0,0,0,0,1,1],
                   'B': [1,2,3,5,4,2,5],
                   'C': [5,3,4,1,1,2,3]})

a_group_desc = df.groupby('A').describe()
print(a_group_desc)

      B                                            \
  count mean       std  min   25%  50%   75%  max   
A                                                   
0   5.0  3.0  1.581139  1.0  2.00  3.0  4.00  5.0   
1   2.0  3.5  2.121320  2.0  2.75  3.5  4.25  5.0   

      C                                            
  count mean       std  min   25%  50%   75%  max  
A                                                  
0   5.0  2.8  1.788854  1.0  1.00  3.0  4.00  5.0  
1   2.0  2.5  0.707107  2.0  2.25  2.5  2.75  3.0  


In [4]:
stacked = a_group_desc.stack()
print(stacked)

                B         C
A                          
0 count  5.000000  5.000000
  mean   3.000000  2.800000
  std    1.581139  1.788854
  min    1.000000  1.000000
  25%    2.000000  1.000000
  50%    3.000000  3.000000
  75%    4.000000  4.000000
  max    5.000000  5.000000
1 count  2.000000  2.000000
  mean   3.500000  2.500000
  std    2.121320  0.707107
  min    2.000000  2.000000
  25%    2.750000  2.250000
  50%    3.500000  2.500000
  75%    4.250000  2.750000
  max    5.000000  3.000000


In [5]:
print(a_group_desc.loc[:,(slice(None),['count','mean']),])

      B          C     
  count mean count mean
A                      
0   5.0  3.0   5.0  2.8
1   2.0  3.5   2.0  2.5


# Utilisation de variables catégorielles

## Contrôle de la version de pandas

In [6]:
import pandas as pd
print(pd.__version__)

0.23.0


## Création de variables catégorielles

In [7]:
import pandas as pd

car_colors = pd.Series(['Bleu', 'Rouge', 'Vert'],
                       dtype='category')

car_data = pd.Series(
    pd.Categorical(
        ['Jaune', 'Vert', 'Rouge', 'Bleu', 'Pourpre'], 
                   categories=car_colors, ordered=False))

find_entries = pd.isnull(car_data)

print(car_colors)
print()
print(car_data)
print()
print(find_entries[find_entries == True])

0     Bleu
1    Rouge
2     Vert
dtype: category
Categories (3, object): [Bleu, Rouge, Vert]

0      NaN
1     Vert
2    Rouge
3     Bleu
4      NaN
dtype: category
Categories (3, object): [Bleu, Rouge, Vert]

0    True
4    True
dtype: bool


## Renommage des niveaux

In [8]:
import pandas as pd

car_colors = pd.Series(['Bleu', 'Rouge', 'Vert'],
                       dtype='category')
car_data = pd.Series(
    pd.Categorical(
        ['Bleu', 'Vert', 'Rouge', 'Bleu', 'Rouge'],
        categories=car_colors, ordered=False))

car_colors.cat.categories = ["Pourpre", "Jaune", "Mauve"]
car_data.cat.categories = car_colors

print(car_data)

0    Pourpre
1      Mauve
2      Jaune
3    Pourpre
4      Jaune
dtype: category
Categories (3, object): [Pourpre, Jaune, Mauve]


## Combinaisons de niveaux

In [9]:
import pandas as pd

car_colors = pd.Series(['Bleu', 'Rouge', 'Vert'],
    dtype='category')
car_data = pd.Series(
    pd.Categorical(
       ['Bleu', 'Vert', 'Rouge', 'Vert', 'Rouge', 'Vert'],
       categories=car_colors, ordered=False))

car_data = car_data.cat.set_categories(
    ["Bleu", "Rouge", "Vert", "Bleu_Rouge"])
print(car_data.loc[car_data.isin(['Rouge'])])
car_data.loc[car_data.isin(['Rouge'])] = 'Bleu_Rouge'
car_data.loc[car_data.isin(['Bleu'])] = 'Bleu_Rouge'

car_data = car_data.cat.set_categories(
    ["Vert", "Bleu_Rouge"])

print()
print(car_data)

2    Rouge
4    Rouge
dtype: category
Categories (4, object): [Bleu, Rouge, Vert, Bleu_Rouge]

0    Bleu_Rouge
1          Vert
2    Bleu_Rouge
3          Vert
4    Bleu_Rouge
5          Vert
dtype: category
Categories (2, object): [Vert, Bleu_Rouge]


# Gestion des données temporelles

## Formatage des dates et des heures

In [10]:
import datetime as dt

now = dt.datetime.now()

print(str(now))
print(now.strftime('%a, %d %B %Y'))

2019-11-10 21:25:26.467912
Sun, 10 November 2019


## Conversion correcte des heures

In [11]:
import datetime as dt

now = dt.datetime.now()
timevalue = now + dt.timedelta(hours=2)

print(now.strftime('%H:%M:%S'))
print(timevalue.strftime('%H:%M:%S'))
print(timevalue - now)

21:25:29
23:25:29
2:00:00


# Gestion des données manquantes

## Repérage des données manquantes

In [12]:
import pandas as pd
import numpy as np

s = pd.Series([1, 2, 3, np.NaN, 5, 6, None])

print(s.isnull())

print()
print(s[s.isnull()])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool

3   NaN
6   NaN
dtype: float64


## Encodage des manquants

In [13]:
import pandas as pd
import numpy as np

s = pd.Series([1, 2, 3, np.NaN, 5, 6, None])

print(s.fillna(int(s.mean())))
print()
print(s.dropna())

0    1.0
1    2.0
2    3.0
3    3.0
4    5.0
5    6.0
6    3.0
dtype: float64

0    1.0
1    2.0
2    3.0
4    5.0
5    6.0
dtype: float64


## Imputation des données manquantes

In [14]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import Imputer

s = [[1, 2, 3, np.NaN, 5, 6, None]]

imp = Imputer(missing_values='NaN',
              strategy='mean', axis=0)

imp.fit([[1, 2, 3, 4, 5, 6, 7]])

x = pd.Series(imp.transform(s).tolist()[0])

print(x)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
dtype: float64


# Tranchage et débitage : filtrer et sélectionner des données

## Tranchage de lignes

In [15]:
x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9],],
             [[11,12,13], [14,15,16], [17,18,19],],
             [[21,22,23], [24,25,26], [27,28,29]]])
x[1]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

## Sélection de colonnes

In [16]:
x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9],],
             [[11,12,13], [14,15,16], [17,18,19],],
             [[21,22,23], [24,25,26], [27,28,29]]])
x[:,1]

array([[ 4,  5,  6],
       [14, 15, 16],
       [24, 25, 26]])

## Débitage (dicing)

In [17]:
x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9],],
             [[11,12,13], [14,15,16], [17,18,19],],
             [[21,22,23], [24,25,26], [27,28,29]]])
print(x[1,1])
print(x[:,1,1])
print(x[1,:,1])
print()
print(x[1:3, 1:3])

[14 15 16]
[ 5 15 25]
[12 15 18]

[[[14 15 16]
  [17 18 19]]

 [[24 25 26]
  [27 28 29]]]


# Concaténation et transformation

## Ajout de nouveaux cas et de nouvelles variables

In [18]:
import pandas as pd

df = pd.DataFrame({'A': [2,3,1],
                   'B': [1,2,3],
                   'C': [5,3,4]})

df1 = pd.DataFrame({'A': [4],
                    'B': [4],
                    'C': [4]})

df = df.append(df1)
df = df.reset_index(drop=True)
print(df)

df.loc[df.last_valid_index() + 1] = [5, 5, 5]
print()
print(df)

df2 = pd.DataFrame({'D': [1, 2, 3, 4, 5]})

df = pd.DataFrame.join(df, df2)
print()
print(df)

   A  B  C
0  2  1  5
1  3  2  3
2  1  3  4
3  4  4  4

   A  B  C
0  2  1  5
1  3  2  3
2  1  3  4
3  4  4  4
4  5  5  5

   A  B  C  D
0  2  1  5  1
1  3  2  3  2
2  1  3  4  3
3  4  4  4  4
4  5  5  5  5


## Suppression de données

In [19]:
import pandas as pd

df = pd.DataFrame({'A': [1,2,3],
                   'B': [4,5,6],
                   'C': [7,8,9]})

df = df.drop(df.index[[1]])
print(df)

df = df.drop('B', 1)
print()
print(df)

   A  B  C
0  1  4  7
2  3  6  9

   A  C
0  1  7
2  3  9


## Trier et mélanger

In [20]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'A': [2,1,2,3,3,5,4],
                   'B': [1,2,3,5,4,2,5],
                   'C': [5,3,4,1,1,2,3]})

df = df.sort_values(by=['A', 'B'], ascending=[True, True])
df = df.reset_index(drop=True)
print(df)

index = df.index.tolist()
np.random.shuffle(index)
df = df.loc[df.index[index]]
df = df.reset_index(drop=True)
print()
print(df)

   A  B  C
0  1  2  3
1  2  1  5
2  2  3  4
3  3  4  1
4  3  5  1
5  4  5  3
6  5  2  2

   A  B  C
0  5  2  2
1  2  3  4
2  3  4  1
3  4  5  3
4  2  1  5
5  3  5  1
6  1  2  3


# Agrégation des données par niveau

In [21]:
import pandas as pd

df = pd.DataFrame({'Mappe': [0,0,0,1,1,2,2],
                   'Valeurs': [1,2,3,5,4,2,5]})

df['S'] = df.groupby('Mappe')['Valeurs'].transform(np.sum)
df['M'] = df.groupby('Mappe')['Valeurs'].transform(np.mean)
df['V'] = df.groupby('Mappe')['Valeurs'].transform(np.var)

print(df)

   Mappe  Valeurs  S    M    V
0      0        1  6  2.0  1.0
1      0        2  6  2.0  1.0
2      0        3  6  2.0  1.0
3      1        5  9  4.5  0.5
4      1        4  9  4.5  0.5
5      2        2  7  3.5  4.5
6      2        5  7  3.5  4.5
